app = "movaa-service-v1"
primary_region = "iad"

[build]
image = "duzaq/movaa-service:v1"

[processes]
#app = "npm start" 
app = "supervisord -n"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
memory_mb = 256
